### ISSUE TITLE
Issue not removed from Bounty List after manually closing issue

### ISSUE THREAD

**Issue by pablanopete** [status-im/open-bounty#149] opened 2017-11-06 04:50 UTC
### User Story

As a User I want to remove my bountied issue from the active bounties once I manually close my issue 

### Description

*Type*: Bug

#### Expected behavior
Add issue and close manually, should remove from active bounties after closing.

#### Actual behavior
After closing issue, issue remained on list of active issues. 

### Reproduction
Open a new bounty issue and close issue out manually - Does not remove from Bounties List 

Issue in question - https://github.com/pablanopete/hello-world/issues/3

Screenshot of issue in bounty list
<img width="669" alt="screen shot 2017-11-05 at 11 50 18 pm" src="https://user-images.githubusercontent.com/18363825/32427115-44803ab2-c284-11e7-9b60-7ce000b82dd3.png">

**Comment by annadanchenko** [comment] 2017-11-07 09:24
@pablanopete seems like can't reproduce on test site. Can you close the issue if it works, please?

**Comment by arash009** [comment] 2017-12-06 11:46
Closing issue as cant reproduce.

**Closed by arash009** 2017-12-06 11:46 UTC
