### ISSUE TITLE
Production Workflow

### ISSUE THREAD

**Issue by pablodip** [status-im/open-bounty#271] opened 2018-02-11 21:06 UTC
I am feeling two problems in the current production workflow:

1.) We have several places to organise production: right now two projects on Github. Besides, some issues don't even fit in those two projects, so can't follow any workflow and their progress is more difficult. All that makes us not know well where to look to know what is going on, and avoid us to visualise well the status of the whole production.

2.) The columns in the Github projects don't show well the status of the issues. For example some of the issues in "TODO" aren't actually ready to "do", implement, but many of them are to define, or to design. That makes us not visualise well where the blocking part in the production is.

My proposals to solve those problems are these:

1.) Have just one project on Github, with the normal workflow that we want to follow in the SOB. We can put there any issues that needs to follow the normal workflow, which are almost all issues. And if we ever have any other workflow, we can have a new project, but only for a different workflow, not for a different group of cards. If we want to group cards by type, we can just tag them, and they can be filtered in the project.

2.) For this we decided to use tags, but we just defined two "designing" and "developing", and thinking more about it I don't think that tags makes us visualse well the status. That is why visualising the status is precisely the purpose of columns. So even though we might end up with more columns, if we really have all those steps in the production, I think it is worth using them. I would add these ones, "To Define", "Defining" "To Design", "Designing", "To Develop", "Developing". Those are just four more columns than the current ones.

I think that both of those changes together will allow us to visualise better the whole production and to make it flow more. :)

Let me know what you think. :)

**Comment by arash009** [comment] 2018-02-12 14:37
Thanks for the suggestions @pablodip . I'm happy with the point 2 re additional columns. On point 1 and having just 1 project, I think its a good idea to combine the 2 current projects, but I'm unsure about putting the entire backlog in the project then.

For one, we have alot of issues and we continuously create more. Having all new items in the project means having to continuously priorities the to-do list (which is both good and bad)

The other point is about having a pre-defined scope of work for releases. If we can group certain features together, then we can size them, estimate them, and come up with a timeline for implementation and release. So once we deliver SOB v2, we can think about v3 and so on.

What if we have projects defined based on scope and timeframes? So any new urgent issues that come up can be added to current project, but then we can have prioritisation and scoping exercise to define scope for SOB v3 (which could have say a Q2 release date), and then others?

**Comment by pablodip** [comment] 2018-02-13 07:59
@arash009 Those are nice problems to solve. :) I am going to number them so that we can distinguish them better.

3.) Regarding having the whole backlog, I think that we could just have any number of issues in Github, but as soon as we want to prioritise them or they get started, we add them to the project, so that they follow the workflow. What do you think?

4.) As for grouping issues, we could just label them, and they can be filtered in the project. Not totally convinced about a project per group, because: a.) Every time that a project is added the whole team needs to add checking it to their habits, so that we need changing habits and more places to check. b.) There are constantly new issues, and we are just going to add them to the current project, that is actually not representing a current project by scope, but by time. I would personally start with the smallest possible solution (1 project) and would try to use the tools that it has (columns and labels) to represent our organisational needs. And then we can see the limitations/problems that we feel.

5.) Another thing to consider: we are representing issues in the project, but not pull requests. And for the issues that we handle it is okay, but for the ones coming as bounties, what we actually want to handle is first the pull request, and then the issue. How about adding the external pull requests that are ready to test to the "TO QA" column instead of the issue? And once a pull request is merged, the original issue will move as well to the "Done" column.

**Comment by martinklepsch** [comment] 2018-02-13 13:03
> The other point is about having a pre-defined scope of work for releases. If we can group certain features together, then we can size them, estimate them, and come up with a timeline for implementation and release. So once we deliver SOB v2, we can think about v3 and so on.

Couldn't we use Milestones for this? I'm not very familiar with how Milestones and Projects interact but I assume that should work?

**Comment by churik** [comment] 2018-02-13 13:16
3) I think that we can prioritize issues during our stand-ups or if issues are urgent/blockers for anyone - in Slack channel. And I personally would be happy with one project instead of two.
4) I believe that labels and columns are completely enough for organization needs. We just need to add several columns and document how and when use labels.
5) Heavy plus! Testing PRs - not issues - is common practice. Status-react team tests PRs, not issues as well.

**Comment by pablodip** [comment] 2018-02-13 14:34
@martinklepsch Regarding milestones, they are just if we set a goal in a group of issues. I personally don't like that that practice unless in very certain occasions, since it involves move organisation work, and allows less auto-organisation. Here we are more in a continuous flow I think, at least for now.

@churik 

5.) How should we organise together both issues and pull requests? For example, if we have an issue  with a pull request, where should each one be? The issue in "Doing" until it is in Prod, and the pull request following the "Testing" flow? Or both together? But what if there are several pull requests for the same issue? :)

**Comment by churik** [comment] 2018-02-13 15:40
5) Hm, let's see. I status-react - there are several projects with different goals - one of them is  'Pipeline for QA' - which includes only issues which should be tested by QA. 
I suggest DON'T move issues to test at all, except only non-reproducible issues (so, I just need to verify that they are not reproducible)
Basically I suggest -  columns 'To define', 'In Bounty', 'Defining', 'To design' 'Designing', 'To develop', 'Developing' - for issues
Columns 'Developing','To test', 'Testing', 'Ready to merge', 'Done' - for PRs

I see 3 different scenarios:
* Issue is feature/enhancement
Here we should have this issue in Project until we developing it. Several PRs can be linked as parts of this feature (i.e. sorting/filtering feature).
Each PR should be independent, so includes implementation of particular part of this feature.
Feature (issue) is in 'developing' state until we decided that it is ready (last PR is merged and deployed).

* Issue is bug
As for me ideal workflow looks like - we have 1 PR per 1 issue  and when we need to fix some issue in particular PR - we just commit changes to this PR, so don't create new one.Thus when issue-bug is in 'Developing' stage, I suggest to remove it from project (not from GH, but from project), add a PR with fix in project in 'TO TEST' stage (if it should be tested). I will be responsible to maintain all issues and close them when associated PR moves to master (but I think GH already did this job), or take it back with 'Tested: Issues' in 'Developing' state until all issues will be fixed
* Issue is just scope of questions/discussions (like this one)
Just shouldn't appear in project.

**Comment by pablodip** [comment] 2018-02-14 06:41
@churik That is great, thanks a lot! :)

5.)

a.) Agree with having two projects, one for issues and another one for pull requests, since they can't follow the same workflow. How about naming them like "Pipeline For Issues" and "Pipeline For Pull Requests"?

b.) Why is the `In Bounty` column at the left of `Defining`? A bounty is already defined, designed, and has passed `To Develop` and decided to be a bounty. So my suggestion is to place it at the right of `To Develop`.

c.) How about adding `Reviewing` at the right of `Developing` in the pipeline for pull requests?

d.) Regarding `Issue is feature/enhancement`, agree with what you said, just that should be temporary until we can use testing environments for everything, then an issue should be solved in a single pull request.

e.) Regarding `Issue is bug`, my suggestion is to just follow the same workflow as for features, so that we can just automatise it and not get confused. So we could have an issue for a bug, and then any pull requests that fix that issue, and when a pull request is merged, the bug issue is considered solved.

f.) Regarding `questions/discussions`, totally agree. In this issue I used the label `organisation`, in case we want to filter them better.

cc @arash009

**Comment by churik** [comment] 2018-02-14 08:05
a) yes, we can. Names seems to me fine.
b) agree, but also we should think how to deal with PR from external contributors, at least for now
c) agree as well
d) in case when `Issue is feature/enhancement` - it can be pretty large and we need to split it, so I think in this case we can create several PRs as parts of big story.

**Comment by pablodip** [comment] 2018-02-14 11:15
b.) The only way we have to deal with pull requests from external contributors is to merge them in `develop`. They could follow the same described workflow, but being merged in `develop`, and we couldn't ask for any changes after merging for now, since the bounty would already be given. Not ideal at all. :S

d.) I think that better than several pull requests would be to split a big issue in several issues, starting with MVPs, and if we want to track them together, we can use filters. What do you think?

**Comment by martinklepsch** [comment] 2018-02-14 14:03
@churik @pablodip would one of you be up to summarize the proposed process in a markdown file (in `doc/`) and propose that through a PR?

I've read all comments and they all seem sensible just a bit hard to piece the entire picture together from various comments 😅 

> d.) I think that better than several pull requests would be to split a big issue in several issues, starting with MVPs, and if we want to track them together, we can use filters. What do you think?

Small issues + small PRs :+1: 

> Regarding milestones, they are just if we set a goal in a group of issues. I personally don't like that that practice unless in very certain occasions, since it involves move organisation work, and allows less auto-organisation. Here we are more in a continuous flow I think, at least for now.

Without wanting to push for the use of milestones I'm not sure I understood why milestones prevent auto organisation. I'm not suggesting to use them in the traditional waterfall sense but rather as "buckets if issues belonging to a bigger objective". In my opinion SOBv2 could be treated as a milestone. The project boards structure should be the same no matter if we're working on SOBv2 or v5 or some other sub project (e.g. Landing Page). 

We also wouldn't have to use Milestones as Github provides them but could model something similar using issues (e.g. `M-SOBv2`, `M-LandingPage`). This would allow items to belong to multiple buckets ("milestones").

**Comment by pablodip** [comment] 2018-02-19 06:23
6.) Who should merge the PRs? To me the creator as much as possible, but we have one problem: from when a PR is tested by QA to where the PR is merged by the creator, there might be a delay, so the PR would need updating and the code might have changed. Proposal: QA could merge PRs when they pass QA testing. That way all PRs that QA tests would be up to date, since QA can use the `Update branch` button of GitHub (or ask for updating to the creator if it has conflicts) just before testing so that all QA testing would be done in up-to-date branches, and they wouldn't become outdated because they are merged right after a positive testing. What do you think?

**Comment by churik** [comment] 2018-02-19 07:23
6) @pablodip in this case we don't need column 'Ready to merge at all'. But we should have some stage between merging some bunch  of PRs to develop and deployment to master branch. Because I cannot guarantee that pieces, which works separately, will work together a same way.

**Comment by pablodip** [comment] 2018-02-19 08:11
6.)

> in this case we don't need column 'Ready to merge at all'.

Good point! Since the merge we're talking about doesn't mean to get to production, but `develop` for now, we can group them there, and when we deploy to production we can move them to `Done`. What do you think?

> > But we should have some stage between merging some bunch of PRs to develop and deployment to master branch. 

That stage could be `develop` for now, until we have `staging`. Did you mean that?

> Because I cannot guarantee that pieces, which works separately, will work together a same way.

This would be precisely the point of this. When you test and merge, you can test always up-to-date pull requests, so if you merge one, the next one that you test should be updated with what you just merged. And right now when you test, you test a pull requests, but without enforcing that it is up-to-date.

And sure the responsibility of the deploy to production isn't yours, that's why we could have that stating stage (`develop` for now), and we devs should deploy to production.

> And we should define probably milestone, as @martinklepsch says, in order to confirm WHEN we should merge together and update master branch with fresh develop branch

I personally don't think that milestones should have to do with deployments, but more with visualisation of certain goals. To me any pull request should be ready to prod, so any pull request that you merge to develop should be able to go to prod at any time, because we devs could deploy develop to prod at any time.

**Comment by churik** [comment] 2018-02-19 09:49
> Since the merge we're talking about doesn't mean to get to production, but develop for now, we can group them there, and when we deploy to production we can move them to Done. What do you think?

I just rename column to 'Merged to develop' and I need to know when we plan to update prod in advance.
For this I think not bad idea is to define who is responsible for release (I mean to warn me in advance and to deploy actually develop when it will be ready to deploy)

> To me any pull request should be ready to prod, so any pull request that you merge to develop should be able to go to prod at any time, because we devs could deploy develop to prod at any time. What do you think?

It is in ideal word, but in reality I believe that we need to do regression testing  around of areas related to merged PRs. I saw a lot of cases when features that work great separately, can break anything else when they are merged.
I hope that regression testing will be automated in future any way.

**Comment by martinklepsch** [comment] 2018-02-19 09:55
##### Who merges PRs?
My vote goes to @churik, or author, or any reviewer as soon as the `Tested-OK` label has been added. We should aim for fast turnaround cycles so I think it is very important that we try to minimize bottlenecks which we can do here by allowing most people to merge.

**Comment by pablodip** [comment] 2018-02-19 12:07
@churik 

> I need to know when we plan to update prod in advance.

Why exactly? Develop should be considered as stable as prod, just we want to move things from develop to prod when we are able to react to any possible problem.

> It is in ideal word, but in reality I believe that we need to do regression testing around of areas related to merged PRs. I saw a lot of cases when features that work great separately, can break anything else when they are merged.

What are you proposing exactly? You will always be testing up-to-date branches, so you can test regressions even before merging them to develop. If you ever find something in develop that has any problems before having landed production, you can just let us know that develop is dirty.

@martinklepsch 

> My vote goes to @churik, or author, or any reviewer as soon as the Tested-OK label has been added.

That label isn't needed with the proposed merging workflow, because if re rely on a label to merge we allow time to pass and branches to become outdated, which is precisely what we wanna avoid with the workflow.

**Comment by churik** [comment] 2018-02-27 13:54
currently described:
https://github.com/status-im/open-bounty/blob/develop/doc/development_workflow.md
https://github.com/status-im/open-bounty/blob/develop/doc/core_testing_workflow.md

**Closed** 2018-02-27 13:54 UTC
Labels: organisation
