### ISSUE TITLE
Twitter Bounty Alerts

### ISSUE THREAD

**Issue by steveklebanoff** [status-im/open-bounty#38] opened 2017-03-15 00:05 UTC
### User Story

As a user, I want to get updated via twitter every time there is a new bounty available

### Solution
Every time a new bounty is posted, post to twitter account using twitter API.  Store twitter credentials in secure way. Don't check in any credentials, instead provide example config for users deploying the app to set their twitter token.  Provide instructions on how to obtain a twitter token.

**Comment by tpatja** [comment] 2017-03-15 07:51
We could have the commitETH twitter account tweet whenever a new bounty is opened and/or balance updated.

**Comment by arash009** [comment] 2017-12-06 10:30
This is essentially a duplicate of https://github.com/status-im/open-bounty/issues/52

Closing to track feature on https://github.com/status-im/open-bounty/issues/52

**Closed by arash009** 2017-12-06 10:30 UTC
Labels: enhancement
