### ISSUE TITLE
Redirect to main test domain when login to custom PR domain

### ISSUE THREAD

**Issue by churik** [status-im/open-bounty#281] opened 2018-02-13 16:49 UTC
### User Story

As a QA, I want to test each PR separately.

### Description
*Type*: Feature
*Summary*: when I log in to particular PR custom domain name, I'm redirected to https://openbounty.status.im:444/app

#### Expected behavior
logged in and redirected to PR custom domain name

#### Actual behavior
after login I redirected to https://openbounty.status.im:444/app

### Reproduction

- Open Status (any deployed PR-XYZ)
- Tap on login
- Enter valid credentials

**Comment by siphiuel** [comment] 2018-02-13 16:54
This is caused by invalid `redirect_uri` for GitHub OAuth App. `redirect_uri` sent in the authorization request should be identical to the URI specified in the OAuth App configuration.

**Comment by martinklepsch** [comment] 2018-02-14 23:16
The only way to make this work seems to have separate Github Apps for different environments. I opened a [thread on the GitHub Platform Forum](https://platform.github.community/t/same-app-in-multiple-environments/5012) to ask for advice around this issue.

If nothing fruitful comes out of this discussion we might want to look into scripting the creation of GitHub apps using a headless Chrome/[puppeteer](https://github.com/GoogleChrome/puppeteer).

**Comment by pablodip** [comment] 2018-02-15 07:38
@martinklepsch Please, let us know how that goes on, since this is a high priority issue that blocks us to test pull requests separately.

**Comment by oskarth** [comment] 2018-02-15 07:49
Maybe the solution is to loosen constraint of testing each PR separately and do nightly testing/testing of staging instead? It's virtually free to revert commit if it is bad. This is similar to what we are moving towards in status-react.

**Comment by pablodip** [comment] 2018-02-15 08:09
@oskarth We're already testing the `develop` branch, but it's a great limitation as we're already feeling with a few pull requests. :)

**Comment by martinklepsch** [comment] 2018-02-16 13:24
I think we can close this now that @v2nek set up a separate testing environment for @churik where she can deploy PRs on-demand?

**Comment by churik** [comment] 2018-02-16 13:26
we can close it now, at least till I'm only QA in open-bounty team)

**Closed** 2018-02-16 13:26 UTC
Labels: high-priority
